version: "3.7"

services:
  app:
    build: .
    image: node:12-alpine
    command: sh -c "npm install && npm run start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app

  mongo:
    image: mongo
    restart: always
    ports:
      - 3005:3005
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example